site_name: embed
site_url: https://embed.whinyaan.xyz
repo_url: https://github.com/whinee/embed
site_description: |-
  Base64 Embeds!
site_author: whi~nyaan!
copyright: Copyright &copy; 2022 whitespace_negative

theme:
  name: material
  locale: en
  include_search_page: false
  search_index_only: true
  language: en

  font:
    text: Roboto
    code: Roboto Mono

  static_templates:
    - 404.html

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.indexes

  palette:
    -
      scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    -
      scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

markdown_extensions:
  -
    pymdownx.superfences:
      custom_fences:
        -
          name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    -
      icon: fontawesome/brands/github
      link: https://github.com/whinee/embed
    -
      icon: fontawesome/brands/twitter
      link: https://twitter.com/whi_nyaan

plugins:
  - search
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true

nav:
  - Home: /
  - License agreement: /license